### ISSUE TITLE
Generic "Raw" class discussion

### ISSUE THREAD

**Issue by SamWhited** [photoshell/rawphoto#1]
I've merged in [`raw.py`](https://github.com/photoshell/rawphoto/blob/master/rawphoto/raw.py) from Photoshell, and am going to modify it to be an immutable `Raw` class which opens a file (using the correct raw parser depending on the file type) and gives you a general way to get metadata, raw image data, etc.

Currently, I was thinking about making `Raw` a named tuple and giving it the following fields `raw_image`, `other_images`, `metadata`. Is there anything else it needs?

Metadata would be its own named tuple (see photoshell/photoshell#82), and images would be a named tuple with `offset`, `length`, and `data` properties (where `data` is a property which reads the actual data as bytes the first time its called and caches it until the cache is flushed or the object is destroyed).

Thoughts on this general layout?

/cc @campaul

**Comment by SamWhited** [comment]
Actually, if I'm going to have an `other_images` array or dict, I might as well not have a separate `raw_image` and just make `raw` one of the things in the array or dict. Keep all the images (raw, thumbnail, large-thumbnail, etc.) in one place.

**Comment by campaul** [comment]
Right now photoshell only needs the metadata, so it would be nice to have a really clean way to get that up front. We can think through a more comprehensive structure once we support more raw formats and know more about what they provide.

For the time being I think we can just have functions like `rawphoto.metadata(file_path)` and `rawphoto.raw_image(file_path)`. That should allow us to build it a piece at a time without defining an overall data structure up front.

**Comment by SamWhited** [comment]
Metadata still needs to be extracted into its own class probably, but it's small enough for now that it's not important. Closing this discussion.
