### ISSUE TITLE
Establish plan for libraw bindings

### ISSUE THREAD

**Issue by campaul** [photoshell/rawphoto#9]
This is an extensive change to the rawphoto library that we've been discussing and we need to map out what the changes will entail. I think the following steps are necessary, but I'd like to open this ticket for general discussion.
- Establish an API - we should define the API for rawphoto to be compatible with what libraw provides so we can easily wrap it.
- Establish test procedures - we should have some set of photos from various cameras that we can test against to ensure everything is working.
- Establish fallback behavior - current rawphoto is "pure python" and I think we should strive to maintain that wherever possible. This means if libraw is not present we should fall back to a python implementation if one exists.

**Comment by campaul** [comment]
To the users of this library, if it is installed without libraw it should "just work", but if it is installed alongside libraw it should "just work" much faster and with support for more hardware.

**Comment by SamWhited** [comment]
This is another thing we should just sit down with some 🍺 and hash out: no distractions, just a copy of the libraw docs and something to take notes on.

**Comment by SamWhited** [comment]
I have added this issue to my [photoshell roadmap proposal](https://github.com/photoshell/photoshell/wiki/Proposal:-Roadmap-%282015-04%29).

**Comment by SamWhited** [comment]
This issue is no longer valid as we decided to make a new library ([rawkit](https://github.com/photoshell/rawkit)) instead and keep this library around for educational purposes. Closing this issue.
